In [3]:
import pickle
import pandas as pd
from os import listdir
from os.path import isfile, join, isdir


# Simply for loading results generated by calc_baselines.py

In [41]:
def format(raw):
    return pd.DataFrame(
        [
            [raw[x][2][1].detach().cpu().numpy(), raw[x][3][1].detach().cpu().numpy()]
            for x in raw.keys()
        ],
        index=raw.keys(),
    )

# Correlation Baseline

In [61]:
# Datsets of 5/7/10/12/15 vars.
pd.read_csv("scores/compute_C.csv", index_col=0)

M_C     Std_C
0  0.058117  0.001337
1  0.096283  0.003553
2  0.171475  0.004106
3  0.229816  0.005856
4  0.342012  0.006172

In [43]:
synth = pickle.load(open("scores/corr_test_auroc.p", "rb"))
synth2 = pickle.load(open("scores/corr_test_scale_up_auroc.p", "rb"))

aero = pickle.load(open("scores/aerosol_corr_test_auroc.p", "rb"))
river = pickle.load(open("scores/river_corr_test_auroc.p", "rb"))
kura = pickle.load(open("scores/kuramoto_corr_test_auroc.p", "rb"))

In [44]:
format(synth)

0           1
SL      0.9993599    0.996957
ML      0.9988861   0.9965359
SNL    0.93239415  0.94297427
MNL     0.9324211   0.9370265
LNL    0.90118945   0.9457957
XLNL    0.9095715   0.9345094
joint   0.9481106  0.99738514

In [45]:
format(synth2)

0           1
scale_up    0.9991704   0.9968045
scale_up_2  0.9985823  0.99296653
scale_up_3  0.9973241  0.97637033
scale_up_4  0.9966355   0.9613055
scale_up_5  0.9948303  0.91737527

In [54]:
kura[0][1],river[1], aero

(tensor(0.6020), tensor(1.0000), tensor(0.4527))

# Var baseline

In [56]:
synth = pickle.load(open("scores/var_test_auroc.p", "rb"))
synth2 = pickle.load(open("scores/var_test_scale_up_auroc.p", "rb"))

#aero = pickle.load(open("scores/aerosol_corr_test_auroc.p", "rb"))
#river = pickle.load(open("scores/river_var_test_auroc.p", "rb"))
#kura = pickle.load(open("scores/kuramoto_var_test_auroc.p", "rb"))

In [57]:
format(synth)

0           1
SL      0.9997213  0.99999857
ML     0.99950457   0.9999966
SNL     0.9287549   0.9464862
MNL    0.93359876   0.9396866
LNL    0.90360534  0.95426846
XLNL    0.9088663   0.9427805
joint  0.86286294  0.92559755

In [58]:
format(synth2)

0           1
scale_up    0.99954927  0.99999034
scale_up_2   0.9993863   0.9999916
scale_up_3  0.99940944  0.99996775
scale_up_4  0.99926454   0.9999354
scale_up_5  0.99931884  0.99986553

In [5]:
def load_res_folder(mypath = "experimental_results/synthetic_data_1_grid_results/std/"):

    onlyfiles = [mypath + f for f in listdir(mypath) if isfile(join(mypath, f))]
    onlyfiles = sorted([x for x in onlyfiles if "summary" in x])
    res = pd.concat([pd.read_csv(x, index_col=0) for x in onlyfiles], axis=1).T
    return  res

# Experiment 1

In [71]:
a = load_res_folder("experimental_results/synthetic_data_1_grid_results/run_1/")
b = load_res_folder("experimental_results/synthetic_data_1_grid_results/run_2/")

In [74]:
res = load_res_folder("experimental_results/synthetic_data_1_grid_results/std/")
res.loc[res["model"].isnull(), "model"] = "small.yaml"
# Provide some summary statistics over the runs.
res = res[["model.model_type", "data.ds_name",'Test1_Auroc', 'Test2_AUROC']]
res["Test1_Auroc"] = res["Test1_Auroc"].astype(float)
res["Test2_AUROC"] = res["Test2_AUROC"].astype(float)

res.groupby(["data.ds_name", "model.model_type"]).mean()

HP                                Test1_Auroc  Test2_AUROC
data.ds_name    model.model_type                          
base            bidirectional        0.999499     0.999961
                convM                0.999336     0.999894
                mlp                  0.999328     0.999933
                transformer          0.999534     0.999968
                unidirectional       0.999558     0.999948
big_base_mirror bidirectional        0.613235     0.626371
                convM                0.506232     0.513293
                mlp                  0.499207     0.498309
                transformer          0.600757     0.621380
                unidirectional       0.599960     0.621146
big_nl          bidirectional        0.709532     0.748808
                convM                0.503338     0.506151
                mlp                  0.501747     0.498722
                transformer          0.518067     0.517684
                unidirectional       0.659285     0.688653
big_poly        bidirectional        0.547126     0.555322
                convM                0.518390     0.518896
                mlp                  0.520201     0.524884
                transformer          0.537860     0.545076
                unidirectional       0.784930     0.828722
nl              bidirectional        0.916400     0.936746
                convM                0.912467     0.934696
                mlp                  0.905332     0.932553
                transformer          0.915942     0.934492
                unidirectional       0.915071     0.936571
poly            bidirectional        0.932779     0.948389
                convM                0.931417     0.948634
                mlp                  0.930141     0.950117
                transformer          0.934952     0.955290
                unidirectional       0.934503     0.954934

# Experiment 1 - Joint

In [75]:
c = load_res_folder("experimental_results/synthetic_data_1_joint_grid_results/splitted_run_1/")

In [76]:
res = load_res_folder("experimental_results/synthetic_data_1_joint_grid_results/std/")

# Provide some summary statistics over the runs.
res = res[["model.model_type", "model",'Test1_Auroc', 'Test2_AUROC']]
res["Test1_Auroc"] = res["Test1_Auroc"].astype(float)
res["Test2_AUROC"] = res["Test2_AUROC"].astype(float)

res.groupby(["model", "model.model_type"]).mean()

HP                            Test1_Auroc  Test2_AUROC
model       model.model_type                          
big.yaml    bidirectional        0.952198     0.962480
            convM                0.867127     0.885812
            mlp                  0.751937     0.760817
            transformer          0.969769     0.977339
            unidirectional       0.946323     0.959416
medium.yaml bidirectional        0.906445     0.920411
            convM                0.869493     0.887307
            mlp                  0.915602     0.928056
            transformer          0.938883     0.949564
            unidirectional       0.894770     0.906847

# Experiment 2

In [11]:
# We dropped quite a bit of runs here somehow. So the results might be underreporting.
d = load_res_folder("experimental_results/synthetic_data_2_grid_results/splitted_run_2/")

In [23]:
d.groupby([ "model","model.model_type", "data.ds_name"]).count()[40:]

HP                                            model.optimizer_lr   
model       model.model_type data.ds_name                          
medium.yaml bidirectional    big_base_mirror                  24  \
                             scale_up                         24   
                             scale_up_2                       24   
            convM            big_base_mirror                  24   
                             scale_up                         24   
                             scale_up_2                       24   
            mlp              big_base_mirror                  24   
                             scale_up                         24   
                             scale_up_2                       24   
            transformer      big_base_mirror                  24   
                             scale_up                         24   
                             scale_up_2                       24   
            unidirectional   big_base_mirror                  24   
                             scale_up                         24   
                             scale_up_2                       24   
small.yaml  bidirectional    big_base_mirror                  24   
                             scale_up_2                       48   
            convM            big_base_mirror                  24   
                             scale_up_2                       72   
            mlp              big_base_mirror                  24   
                             scale_up_2                       48   
            transformer      big_base_mirror                  24   
                             scale_up_2                       71   
            unidirectional   big_base_mirror                  24   
                             scale_up_2                       48   

HP                                            data.batch_size   
model       model.model_type data.ds_name                       
medium.yaml bidirectional    big_base_mirror               24  \
                             scale_up                      24   
                             scale_up_2                    24   
            convM            big_base_mirror               24   
                             scale_up                      24   
                             scale_up_2                    24   
            mlp              big_base_mirror               24   
                             scale_up                      24   
                             scale_up_2                    24   
            transformer      big_base_mirror               24   
                             scale_up                      24   
                             scale_up_2                    24   
            unidirectional   big_base_mirror               24   
                             scale_up                      24   
                             scale_up_2                    24   
small.yaml  bidirectional    big_base_mirror               24   
                             scale_up_2                    48   
            convM            big_base_mirror               24   
                             scale_up_2                    72   
            mlp              big_base_mirror               24   
                             scale_up_2                    48   
            transformer      big_base_mirror               24   
                             scale_up_2                    71   
            unidirectional   big_base_mirror               24   
                             scale_up_2                    48   

HP                                            model.weight_decay   
model       model.model_type data.ds_name                          
medium.yaml bidirectional    big_base_mirror                  24  \
                             scale_up                         24   
                             scale_up_2                       24   
            convM            big_base_mirror                  24   

In [20]:
res = load_res_folder("experimental_results/synthetic_data_2_grid_results/std/")

# Provide some summary statistics over the runs.
#res = res[["model.model_type", "model",'Test1_Auroc', 'Test2_AUROC']]
#res["Test1_Auroc"] = res["Test1_Auroc"].astype(float)
#res["Test2_AUROC"] = res["Test2_AUROC"].astype(float)

#res.groupby(["model", "model.model_type"]).mean()

In [24]:
res.groupby([ "model","model.model_type", "data.ds_name"]).count()

HP                                            seed  hparams_search   
model       model.model_type data.ds_name                            
big.yaml    bidirectional    big_base_mirror     5               5  \
                             scale_up            5               5   
                             scale_up_2          5               5   
                             scale_up_3          5               5   
            convM            big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
                             scale_up_3          5               5   
            transformer      big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
                             scale_up_3          2               2   
            unidirectional   big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
                             scale_up_3          5               5   
medium.yaml bidirectional    big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
            convM            big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
            mlp              big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
            transformer      big_base_mirror     5               5   
                             scale_up            5               5   
            unidirectional   big_base_mirror     5               5   
                             scale_up            5               5   
                             scale_up_2          5               5   
small.yaml  bidirectional    big_base_mirror     5               5   
                             scale_up_2          5               5   
            convM            big_base_mirror     5               5   
            mlp              big_base_mirror     5               5   
            transformer      big_base_mirror     5               5   
            unidirectional   big_base_mirror     5               5   
                             scale_up_2          5               5   

HP                                            model.optimizer_lr   
model       model.model_type data.ds_name                          
big.yaml    bidirectional    big_base_mirror                   5  \
                             scale_up                          5   
                             scale_up_2                        5   
                             scale_up_3                        5   
            convM            big_base_mirror                   5   
                             scale_up                          5   
                             scale_up_2                        5   
                             scale_up_3                        5   
            transformer      big_base_mirror                   5   
                             scale_up                          5   
                             scale_up_2                        5   
                             scale_up_3                        2   
            unidirectional   big_base_mirror                   5   
                             scale_up                          5   
                             scale_up_2                        5   
                             scale_up_3                        5   
medium.yaml bidirectional    big_base_mirror 

# Experiment Kuramoto

In [78]:
e = load_res_folder("experimental_results/kuramoto_grid_results/splitted_run_1/")

In [82]:
res = load_res_folder("experimental_results/kuramoto_grid_results/std/")

# Provide some summary statistics over the runs.
res = res[["model.model_type",'Test1_Auroc']]
res["Test1_Auroc"] = res["Test1_Auroc"].astype(float)

res.groupby([ "model.model_type"]).mean()

HP                Test1_Auroc
model.model_type             
bidirectional        0.852495
convM                0.954027
mlp                  0.824648
transformer          0.888369
unidirectional       0.905020

In [ ]:
# 

In [16]:
corr = pickle.load(open("scores/corr_test_auroc.p", "rb"))
var = pickle.load(open("scores/var_test_auroc.p", "rb"))
# pcmci = pickle.load(open("scores/pcmci_test_auroc.p", "rb"))
# pcmci2 = pickle.load(open("scores/pcmci_test_auroc_joint.p", "rb"))


corr = pd.DataFrame(
    [
        [corr[x][2][1].detach().cpu().numpy(), corr[x][3][1].detach().cpu().numpy()]
        for x in corr.keys()
    ],
    index=corr.keys(),
)
var = pd.DataFrame(
    [
        [var[x][2][1].detach().cpu().numpy(), var[x][3][1].detach().cpu().numpy()]
        for x in var.keys()
    ],
    index=var.keys(),
)
# pcmci = pd.DataFrame([[pcmci[x][0][1].detach().cpu().numpy(), pcmci[x][1][1].detach().cpu().numpy()] for x in pcmci.keys()], index=pcmci.keys() )
# pcmci2 = pd.DataFrame([[pcmci2[x][0][1].detach().cpu().numpy(), pcmci2[x][1][1].detach().cpu().numpy()] for x in pcmci2.keys()], index=pcmci2.keys() )

In [20]:
corr = pickle.load(open("scores/corr_test_auroc.p", "rb"))


In [22]:
corr["LNL"]

[((tensor([0.0000, 0.0000, 0.0000,  ..., 1.0000, 1.0000, 1.0000]),
   tensor([0.0000e+00, 8.6550e-05, 1.7310e-04,  ..., 1.0000e+00, 1.0000e+00,
           1.0000e+00]),
   tensor([1.0000e+00, 8.3439e-01, 8.1610e-01,  ..., 2.1808e-06, 2.0944e-06,
           3.6692e-07])),
  tensor(0.9396)),
 ((tensor([0.0000, 0.0000, 0.0000,  ..., 0.9997, 0.9999, 1.0000]),
   tensor([0.0000e+00, 8.3752e-04, 1.6750e-03,  ..., 1.0000e+00, 1.0000e+00,
           1.0000e+00]),
   tensor([1.0000e+00, 4.4940e-01, 4.3376e-01,  ..., 3.3696e-05, 7.6904e-06,
           2.3486e-06])),
  tensor(0.9158)),
 ((tensor([0.0000, 0.0000, 0.0000,  ..., 0.9997, 0.9999, 1.0000]),
   tensor([0.0000e+00, 8.4388e-04, 1.6878e-03,  ..., 1.0000e+00, 1.0000e+00,
           1.0000e+00]),
   tensor([1.0000e+00, 5.0259e-01, 4.9486e-01,  ..., 2.4641e-05, 1.5831e-05,
           1.7236e-06])),
  tensor(0.9031)),
 ((tensor([0.0000, 0.0000, 0.0000,  ..., 0.9997, 0.9999, 1.0000]),
   tensor([0.0000e+00, 7.9681e-04, 1.5936e-03,  ..., 1.0000e